/* 
  보통 head 태그 안에다가 적을 내용들을 layout파일에 적는다
  전역적으로 존재하는 상단메뉴같은 ui
*/
import Link from "next/link";
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
        <Link href="/">home</Link>
        <Link href="/list">List</Link>
        <Link href="/cart">cart</Link>
      </div>
        {children}</body>
    </html>
  )
}
